#!/system/bin/sh
#
echo "3" > /proc/sys/vm/page-cluster;
echo "0" > /proc/sys/vm/laptop_mode; 
echo "90" > /proc/sys/vm/dirty_ratio; 
echo "85" > /proc/sys/vm/dirty_background_ratio;  

echo "1000" > /proc/sys/vm/dirty_expire_centisecs
echo "3000" > /proc/sys/vm/dirty_writeback_centisecs
