#!/bin/sh

################################################################################
#                                                                              #
# Copyright c 2009-2011  WonderMedia Technologies, Inc.   All Rights Reserved. #
#                                                                              #
# This PROPRIETARY SOFTWARE is the property of WonderMedia Technologies, Inc.  #
# and may contain trade secrets and/or other confidential information of       #
# WonderMedia Technologies, Inc. This file shall not be disclosed to any third #
# party, in whole or in part, without prior written consent of WonderMedia.    #
#                                                                              #
# THIS PROPRIETARY SOFTWARE AND ANY RELATED DOCUMENTATION ARE PROVIDED AS IS,  #
# WITH ALL FAULTS, AND WITHOUT WARRANTY OF ANY KIND EITHER EXPRESS OR IMPLIED, #
# AND WonderMedia TECHNOLOGIES, INC. DISCLAIMS ALL EXPRESS OR IMPLIED          #
# WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET       #
# ENJOYMENT OR NON-INFRINGEMENT.                                               #
#                                                                              #
###################################################################

if [ ! -e /data/wmtpref/etc/ppp ]; then
	mkdir -p /data/wmtpref/etc
	cp /system/etc/ppp /data/wmtpref/etc/ppp -rf
fi
chmod -R 777 /data/wmtpref

#Check if dvfs is supported.
dvfs=`wmtenv get wmt.cpufreq.param | grep 984`
if [ "${dvfs}" = "" ];then
	echo "No DVFS Suported"
else
	echo "DVFS Suported"
	echo ondemand > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi

